const server = require('./server.mjs')
const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const fileUpload = require('express-fileupload')
const app = express()
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(cors())
app.use(fileUpload({}))
app.get('/users', async (req, res) => await server.User.get(req, res))
app.get('/passSubj', async (req, res) => await server.PassSubj.get(req, res))
app.get('/currSubj', async (req, res) => await server.CurrSubj.get(req, res))
app.get('/lessons', async (req, res) => await server.Lesson.get(req, res))
app.get('/marks', async (req, res) => await server.Mark.get(req, res))
app.get('/checking', async (req, res) => await server.Checking.get(req, res))
app.get('/homeworks', async (req, res) => await server.Homework.get(req, res))
app.get('/lessById', async (req, res) => await server.LessById.get(req, res))
app.get('/passSubjById', async (req, res) => await server.PassSubjById.get(req, res))
app.get('/currSubjById', async (req, res) => await server.CurrSubjById.get(req, res))
app.get('/homByLess', async (req, res) => await server.HomByLess.get(req, res))
app.get('/journal/passSubj', async (req, res) => await server.PassSubjOfJourn.get(req, res))
app.get('/journal/currSubj', async (req, res) => await server.CurrSubjOfJourn.get(req, res))
app.get('/journal/groupById', async (req, res) => await server.JournGroupById.get(req, res))
app.get('/journal/groups', async (req, res) => await server.JournGroup.get(req, res))
app.get('/journal/groupByName', async (req, res) => await server.JournGroupByName.get(req, res))
app.get('/journal/currSubjByUser', async (req, res) => await server.CurrSubjOfJournByUser.get(req, res))
app.get('/journal/groupsOutOfArch', async (req, res) => await server.JournGroupOutOfArch.get(req, res))
app.get('/journal/usersByGroup', async (req, res) => await server.JournUserByGroup.get(req, res))
app.get('/journal/users', async (req, res) => await server.JournUser.get(req, res))
app.get('/journal/lessons', async (req, res) => await server.JournLess.get(req, res))
app.get('/journal/subjects', async (req, res) => await server.JournSubj.get(req, res))
app.get('/journal/lessBySubj', async (req, res) => await server.JournLessBySubj.get(req, res))
app.get('/journal/checking', async (req, res) => await server.JournCheck.get(req, res))
app.get('/journal/userById', async (req, res) => await server.JournUserById.get(req, res))
app.get('/journal/homeworks', async (req, res) => await server.JournHomById.get(req, res))
app.get('/journal/lessById', async (req, res) => await server.JournLessById.get(req, res))
app.post('/', async (req, res) => await server.CheckIn.post(req, res))
app.post('/file', (req, res) => server.File.post(req, res))
app.post('/homework', async (req, res) => await server.Work.post(req, res))
app.post('/journal', async (req, res) => await server.Journal.post(req, res))
app.post('/journal/subjArch', async (req, res) => await server.SubjArchOfJourn.post(req, res))
app.post('/journal/currSubj', async (req, res) => await server.CurrSubjOfJournByName.post(req, res))
app.post('/journal/edSubj', async req => await server.EdJournSubj.post(req))
app.post('/journal/addSubj', async req => await server.AddJournSubj.post(req))
app.post('/journal/groupArch', async (req, res) => await server.GroupArchOfJourn.post(req, res))
app.post('/journal/edGroup', async req => await server.EdJournGroup.post(req))
app.post('/journal/exception', async (req, res) => await server.JournExc.post(req, res))
app.post('/journal/inclusion', async (req, res) => await server.JournIncl.post(req, res))
app.post('/journal/creatGroup', async req => await server.CreatJournGroup.post(req))
app.post('/journal/homework', async req => await server.JournHom.post(req))
app.post('/journal/comment', async (req, res) => await server.JournComm.post(req, res))
app.post('/journal/mark', async (req, res) => await server.JournMark.post(req, res))
app.listen(3000)